export const WORK_FROM_YEAR_TIME_STAMP = new Date('2013/05/01').valueOf(); // Might not be accurate due to the different timezone setting.
export const LINKEDIN_URL = 'https://www.linkedin.com/in/jimlin0958/';
export const GITHUB_URL = 'https://github.com/JimLin94';
export const GITHUB_REPO_NAME = 'resume';
export const PROFILE_IMG_PATH = `/${GITHUB_REPO_NAME}/avatar.jpg`;
export const LANDSCAPE_PROFILE_META_IMG_PATH = `/og-profile.jpg`;
export const PDF_PATH = `/${GITHUB_REPO_NAME}/resume-2023-v2.pdf`;
export const GIT_PAGE_URL = `https://jimlin94.github.io/${GITHUB_REPO_NAME}`;
export const EMAIL = 'jimlin7694@gmail.com';
export const SITE_NAME = "Jim's resume";
export const AUTHOR = 'Jim Lin';
export const DESCRIPTION = 'Looking for a Front-End developer?';
